#!/bin/bash

BRANCH=master
TEST_DIR=$(cd `dirname "${BASH_SOURCE[0]}"` && pwd)
export PLUGIN_PATH=$TEST_DIR/tmp
export CONSUL_STORE=https://raw.githubusercontent.com/sequenceiq/consul-plugins-install/$BRANCH/test/
export LOGFILE=$PLUGIN_PATH/test.log

plugn(){
  debug plugn $@
}

. $TEST_DIR/../install-plugin

export PAYLOAD="git://github.com/sequenceiq/consul-plugins-titan git1"
main

export PAYLOAD="https://github.com/sequenceiq/consul-plugins-titan.git git2"
main

export PAYLOAD="consul://consul consul"
main

export PAYLOAD="https://raw.githubusercontent.com/sequenceiq/consul-plugins-install/$BRANCH/test/example.tar tar"
main

export PAYLOAD="https://raw.githubusercontent.com/sequenceiq/consul-plugins-install/$BRANCH/test/example.zip zip"
main

if [ 5 -ne $(find $PLUGIN_PATH/available -name plugin.toml | wc -l) ]; then
  echo "FAILED, some of the plugins are missing!"
  exit 1
fi

echo "git1" > $PLUGIN_PATH/permanent-plugins
echo "git2" >> $PLUGIN_PATH/permanent-plugins

. $TEST_DIR/../cleanup-plugin
main

if [ 2 -ne $(find $PLUGIN_PATH/available -name plugin.toml | wc -l) ]; then
  echo "FAILED, some of the permanent plugins are accidently removed!"
  exit 1
fi

rm -rf $PLUGIN_PATH
