#!/bin/bash

: ${INSTALL_LOGFILE:=/tmp/install_download.log}
: ${DEBUG:=1}

main(){
  read url name;
  debug url=$url name=$name;
  if plugn install $url $name; then
    debug "Plugin ($name) installed successfully."
    plugn enable $name || debug "Couldn't enable plugin.";
    debug "Plugin ($name) enabled successfully."
  else
    debug "Couldn't install plugin from specified URL.";
  fi
}

debug(){
  [[ "$DEBUG" ]] && echo "[DEBUG] $*" >> $INSTALL_LOGFILE
}

[[ "$0" == "$BASH_SOURCE" ]] && main "$@"
