#!/bin/bash

: ${LOGFILE:=/tmp/install_download.log}
: ${DEBUG:=1}

main(){
  url=$(echo $PAYLOAD | cut -d" " -f 1);
  name=$(echo $PAYLOAD | cut -d" " -f 2);
  debug url=$url name=$name;
  if plugn install $url $name; then
    debug "Plugin ($name) installed successfully."
    plugn enable $name || (debug "Couldn't enable plugin." && exit 1);
    debug "Plugin ($name) enabled successfully."
  else
    if [ $? -eq 128 ]; then
      debug "Plugin already installed".
    else
      debug "Couldn't install plugin from specified URL.";
      exit 1;
    fi
  fi
}

debug(){
  [[ "$DEBUG" ]] && echo "[DEBUG] $*" >> $LOGFILE
}

[[ "$0" == "$BASH_SOURCE" ]] && main "$@"
